name: Daily Financial Report

on:
  schedule:
    # Runs every day at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  trigger-daily-report:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Daily Report Workflow
        run: |
          curl -X POST "${{ secrets.N8N_DAILY_REPORT_WEBHOOK_URL }}"
